### ISSUE TITLE
Requires Swift 5.9 (Xcode 15) to compile

### ISSUE THREAD

**Issue by dbii** [liveview-native/liveview-native-swiftui-charts#109]
Current code is not compatible with Swift 5.8 (Xcode 14). The error is:

liveview-native-swiftui-charts/Sources/LiveViewNativeCharts/Modifiers/ZIndexModifier.swift:40:17 Value of type 'ZIndexModifier.Builder.Content' (aka 'any ChartContent') has no member 'zIndex'

which is because zIndex was added in iOS 17

https://developer.apple.com/documentation/charts/chartcontent/zindex(_:)?changes=latest_major

**Comment by carson-katri** [comment]
We now require Xcode 15 to build LiveView Native.
