### ISSUE TITLE
Stack trace

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-native-swiftui-charts#113]
I had an incomplete chart markup but there shouldn't be stack traces from this:

```heex
<Chart>
  <LineMark :for={datum <- @data} y:label={datum} y:value={datum} />
</Chart>
```

I think there should probably be a single try/catch when building elements to prevent errors from happening. We can log out when something isn't correct

**Comment by bcardarella** [comment]
<img width="1819" alt="Screenshot 2024-04-17 at 2 23 36 PM" src="https://github.com/liveview-native/liveview-native-swiftui-charts/assets/18524/ae504636-c063-40b8-91a0-249823a3e743">

**Comment by carson-katri** [comment]
I believe this was related to an issue with the JSON encoding on the server that has been fixed.

**Comment by bcardarella** [comment]
Ok, closing for now
